export const AGENCY_PROFILE_EMAIL_CHANGE_FAIL =
  "AGENCY_PROFILE_EMAIL_CHANGE_FAIL";
export const AGENCY_PROFILE_EMAIL_CHANGE_REQUEST =
  "AGENCY_PROFILE_EMAIL_CHANGE_REQUEST";
export const AGENCY_PROFILE_EMAIL_CHANGE_SUCCESS =
  "AGENCY_PROFILE_EMAIL_CHANGE_SUCCESS";

export const AGENCY_PROFILE_PASSWORD_CHANGE_SUCCESS =
  "AGENCY_PROFILE_PASSWORD_CHANGE_SUCCESS";
export const AGENCY_PROFILE_PASSWORD_CHANGE_REQUEST =
  "AGENCY_PROFILE_PASSWORD_CHANGE_REQUEST";
export const AGENCY_PROFILE_PASSWORD_CHANGE_FAIL =
  "AGENCY_PROFILE_PASSWORD_CHANGE_FAIL";

export const AGENCY_PROFILE_COMMUNICATION_FAIL =
  "AGENCY_PROFILE_COMMUNICATION_FAIL";
export const AGENCY_PROFILE_COMMUNICATION_SUCCESS =
  "AGENCY_PROFILE_COMMUNICATION_SUCCESS";
export const AGENCY_PROFILE_COMMUNICATION_REQUEST =
  "AGENCY_PROFILE_COMMUNICATION_REQUEST";
export const AGENCY_PROFILE_COMMUNICATION_RESET =
  "AGENCY_PROFILE_COMMUNICATION_RESET";

export const GET_AGENCY_PROFILE_COMMUNICATION_FAIL =
  "GET_AGENCY_PROFILE_COMMUNICATION_FAIL";
export const GET_AGENCY_PROFILE_COMMUNICATION_SUCCESS =
  "GET_AGENCY_PROFILE_COMMUNICATION_SUCCESS";
export const GET_AGENCY_PROFILE_COMMUNICATION_REQUEST =
  "GET_AGENCY_PROFILE_COMMUNICATION_REQUEST";

export const AGENCY_PROFILE_COMM_DELETE_REQUEST =
  "AGENCY_PROFILE_COMM_DELETE_REQUEST";
export const AGENCY_PROFILE_COMM_DELETE_SUCCESS =
  "AGENCY_PROFILE_COMM_DELETE_SUCCESS";
export const AGENCY_PROFILE_COMM_DELETE_FAIL =
  "AGENCY_PROFILE_COMM_DELETE_FAIL";

export const AGENCY_PROFILE_COMM_EDITDATA_FAIL =
  "AGENCY_PROFILE_COMM_EDITDATA_FAIL";
export const AGENCY_PROFILE_COMM_EDITDATA_SUCCESS =
  "AGENCY_PROFILE_COMM_EDITDATA_SUCCESS";
export const AGENCY_PROFILE_COMM_EDITDATA_REQUEST =
  "AGENCY_PROFILE_COMM_EDITDATA_REQUEST";

export const AGENCY_PROFILE_JOBS_PROGRESS_REQUEST =
  "AGENCY_PROFILE_JOBS_PROGRESS_REQUEST";
export const AGENCY_PROFILE_JOBS_PROGRESS_SUCCESS =
  "AGENCY_PROFILE_JOBS_PROGRESS_SUCCESS";
export const AGENCY_PROFILE_JOBS_PROGRESS_FAILURE =
  "AGENCY_PROFILE_JOBS_PROGRESS_FAILURE";
