name: Build and Push adifect-frontend

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "development"
      - "releases/**"

env:
  DEV_REPO_NAME: 014481445141.dkr.ecr.us-east-1.amazonaws.com/adifect/dev-adifect
  PROD_REPO_NAME: 014481445141.dkr.ecr.us-east-1.amazonaws.com/adifect/prod-adifect
  GITHUB_SHA: ${{ github.sha }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show workflow inputs
        run: |
          echo BRANCH=${{ github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install yq - portable yaml processor
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Build and Push images
        run: |
          export BRANCH=${GITHUB_REF#refs/heads/}
          export GITHUBPAT=${{ secrets.GITPAT }}
          echo "Login to ECR REPO"
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 014481445141.dkr.ecr.us-east-1.amazonaws.com
          echo "ecr login successful"
          export GIT_COMMIT=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "Build and Push images to ECR"

          if [[ "$BRANCH" == "main" ]];then

                 echo "Build Prod image"
                 docker build --build-arg REACT_APP_BACKEND_API_URL=api.adifect.com --build-arg REACT_APP_FRONTEND_URL=adifect.com -t $PROD_REPO_NAME:adifect_frontend_prod_$GIT_COMMIT .
                 docker push $PROD_REPO_NAME:adifect_frontend_prod_$GIT_COMMIT
                 echo "update image tags"
                 git config --global user.email github-actions@github.com
                 git config --global user.name github-actions
                 git fetch --all
                 git clone https://$GITHUBPAT@github.com/Adifect/infrastructure.git -b master
                 cd infrastructure
                 export PROD_TAG=adifect_frontend_prod_$GIT_COMMIT
                 yq -e '.image.tag = env(PROD_TAG)' -i charts/adifect-frontend/prod-environment/values.yaml
                 git add .
                 git commit -m " update prod image tags:- $PROD_TAG "
                 git push

          elif [[ "$BRANCH" == "development" ]];then

                 echo "Build Dev image"
                 echo "the branch is $BRANCH"
                 docker build -t $DEV_REPO_NAME:adifect_frontend_develop_$GIT_COMMIT .
                 docker push $DEV_REPO_NAME:adifect_frontend_develop_$GIT_COMMIT
                 echo "update image tags"
                 git config --global user.email github-actions@github.com
                 git config --global user.name github-actions
                 git fetch --all
                 git clone https://$GITHUBPAT@github.com/Adifect/infrastructure.git -b master
                 cd infrastructure/
                 export DEV_TAG=adifect_frontend_develop_$GIT_COMMIT
                 yq -e '.image.tag = env(DEV_TAG)' -i charts/adifect-frontend/dev-environment/values.yaml
                 git add .
                 git commit -m " update dev image tags:- $DEV_TAG "
                 git push

          else

                 echo "Build QA Image"
                 docker build --build-arg REACT_APP_BACKEND_API_URL=api-qa.adifect.com --build-arg REACT_APP_FRONTEND_URL=qa.adifect.com -t $DEV_REPO_NAME:adifect_frontend_release_$GIT_COMMIT .
                 docker push $DEV_REPO_NAME:adifect_frontend_release_$GIT_COMMIT
                 echo "update image tags"
                 git config --global user.email github-actions@github.com
                 git config --global user.name github-actions
                 git fetch --all
                 git clone https://$GITHUBPAT@github.com/Adifect/infrastructure.git -b master
                 cd infrastructure/
                 export QA_TAG=adifect_frontend_release_$GIT_COMMIT
                 yq -e '.image.tag = env(QA_TAG)' -i charts/adifect-frontend/qa-environment/values.yaml
                 git add .
                 git commit -m " update dev image tags:- $QA_TAG "
                 git push

          fi
